<br><br><span style="color:red;">This field is required only for keyword position</span><br> <span style="font-weight:bold; font-size:large; ">Language : </span><select  id="language" name="language">
											<option value="lang_us">United States &ndash; English (en-US)</option>
											<option value="lang_uk">United Kingdom &ndash; English (en-UK)</option>
											<option value="lang_au">Australia &ndash; English (en-AU)</option>
											<option value="lang_de">Germany &ndash; German (de-DE)</option>
											<option value="lang_nl">Netherlands &ndash; Dutch (nl-NL)</option>
											<option value="lang_th">Thailand &ndash; Thai (th-TH)</option>
											<option value="lang_ca">Canada &ndash; English (en-CA)</option>
											<option value="lang_tr">Turkey &ndash; Turkish (tr-TR)</option>
											<option value="lang_se">Sweden &ndash; Swedish (sv-SE)</option>
											<option value="lang_dk">Denmark &ndash; Danish (da-DK)</option>
											<option value="lang_in">India &ndash; English (en-IN)</option>
											<option value="lang_ie">Ireland &ndash; English (en-IE)</option>
											<option value="lang_za">South Africa &ndash; English (en-ZA)</option>
											<option value="lang_es">Spain &ndash; Spanish (es-ES)</option>
											<option value="lang_ro">Romania &ndash; Romanian (ro-RO)</option>
											<option value="lang_sg">Singapore &ndash; English (en-SG)</option>
											<option value="lang_id">Indonesia &ndash; Indonesian (id-ID)</option>
											<option value="lang_br">Brazil &ndash; Portuguese (pt-BR)</option>
											<option value="lang_it">Italy &ndash; Italian (it-IT)</option>
											<option value="lang_ca">Canada &ndash; French (fr-CA)</option>
											<option value="lang_fr">France &ndash; French (fr-FR)</option>
											<option value="lang_mx">Mexico &ndash; Spanish (es-MX)</option>
											<option value="lang_fl">Finland &ndash; Finnish (fi-FL)</option>
											<option value="lang_pl">Poland &ndash; Polish (pl-PL)</option>
											<option value="lang_no">Norway &ndash; Norwegian (no-NO)</option>
											<option value="lang_gr">Greece &ndash; Greek (el-GR)</option>
											<option value="lang_nz">New Zealand &ndash; English (en-NZ)</option>
											<option value="lang_ph">Philippines &ndash; English (en-PH)</option>
											<option value="lang_ch">Switzerland &ndash; German (de-CH)</option>
											<option value="lang_ar">Argentina &ndash; Spanish (es-AR)</option>
											<option value="lang_ru">Russia &ndash; Russian (ru-RU)</option>
											<option value="lang_ae">United Arab Emirates &ndash; Arabic (ar-AE)</option>
											<option value="lang_il">Israel &ndash; Hebrew (he-IL)</option>
											<option value="lang_my">Malaysia &ndash; English (en-MY)</option>
											<option value="lang_cl">Chile &ndash; Spanish (es-CL)</option>
											<option value="lang_sk">Slovakia &ndash; Slovak (sk-SK)</option>
											<option value="lang_at">Austria &ndash; German (de-AT)</option>
											<option value="lang_si">Slovenia &ndash; Slovenian (sl-SI)</option>
											<option value="lang_th">Thailand &ndash; English (en-TH)</option>
											<option value="lang_id">Indonesia &ndash; English (en-ID)</option>
											<option value="lang_cn-hk">China &ndash; Chinese (Simplified) (zh-CN-HK)</option>
											<option value="lang_il">Israel &ndash; Arabic (ar-IL)</option>
											<option value="lang_pt">Portugal &ndash; Portuguese (pt-PT)</option>
											<option value="lang_us">United States &ndash; Spanish (es-US)</option>
											<option value="lang_hr">Croatia &ndash; Croatian (hr-HR)</option>
											<option value="lang_il">Israel &ndash; English (en-IL)</option>
											<option value="lang_za">South Africa &ndash; Afrikaans (af-ZA)</option>
											<option value="lang_be">Belgium &ndash; English (en-BE)</option>
											<option value="lang_sa">Saudi Arabia &ndash; Arabic (ar-SA)</option>
											<option value="lang_ro">Romania &ndash; German (de-RO)</option>
											
											<option value="lang_vn">Vietnam &ndash; English (en-VN)</option>
											<option value="lang_lt">Lithuania &ndash; Lithuanian (lt-LT)</option>
											<option value="lang_rs">Serbia &ndash; Serbian (sr-RS)</option>
											<option value="lang_af">Afghanistan &ndash; Persian (ps-AF)</option>
											<option value="lang_dz">Algeria</option>
											<option value="lang_as">American Samoa &ndash; English (en-AS)</option>
											<option value="lang_ad">Andorra &ndash; Catalan (ca-AD)</option>
											<option value="lang_ao">Angola &ndash; Portuguese (pt-AO)</option>
											<option value="lang_ai">Anguilla &ndash; English (en-AI)</option>
											<option value="lang_ag">Antigua and Barbuda &ndash; English (en-AG)</option>
											<option value="lang_am">Armenia &ndash; Armenian (hy-AM)</option>
											<option value="lang_az">Azerbaijan &ndash; Azerbaijani (az-AZ)</option>
											<option value="lang_bs">Bahamas &ndash; English (en-BS)</option>
											<option value="lang_bh">Bahrain</option>
											<option value="lang_bd">Bangladesh &ndash; Bengali (bn-BD)</option>
											<option value="lang_by">Belarus &ndash; Belarusian (be-BY)</option>
											<option value="lang_be">Belgium</option>
											
											
											<option value="lang_bz">Belize </option>
											<option value="lang_bj">Benin &ndash; French (fr-BJ)</option>
											<option value="lang_bo">Bolivia &ndash; Spanish (es-BO)</option>
											<option value="lang_ba">Bosnia and Herzegovina &ndash; Bosnian (bs-BA)</option>
											<option value="lang_bw">Botswana &ndash; Tswana (tn-BW)</option>
											<option value="lang_vg">British Virgin Islands &ndash; English (en-VG)</option>
											<option value="lang_bn">Brunei &ndash; Malay (ms-BN)</option>
											<option value="lang_bg">Bulgaria &ndash; Bulgarian (bg-BG)</option>
											<option value="lang_bf">Burkina Faso &ndash; French (fr-BF)</option>
											<option value="lang_bi">Burundi &ndash; French (fr-BI)</option>
											<option value="lang_kh">Cambodia &ndash; Khmer (km-KH)</option>
											<option value="lang_cm">Cameroon &ndash; French (fr-CM)</option>
											<option value="lang_cv">Cape Verde &ndash; Portuguese (pt-CV)</option>
											<option value="lang_cf">Central African Republic &ndash; French (fr-CF)</option>
											<option value="lang_td">Chad &ndash; French (fr-TD)</option>
											<option value="lang_cc">Cocos Islands &ndash; English (en-CC)</option>
											<option value="lang_co">Colombia &ndash; Spanish (es-CO)</option>
											<option value="lang_ck">Cook Islands &ndash; English (en-CK)</option>
											<option value="lang_cr">Costa Rica &ndash; Spanish (es-CR)</option>
											<option value="lang_ci">C&#244;te d\'Ivoire &ndash; French (fr-CI)</option>
											<option value="lang_cu">Cuba &ndash; Spanish (es-CU)</option>
											<option value="lang_cz">Czech Republic &ndash; Czech (cs-CZ)</option>
											<option value="lang_dj">Djibouti &ndash; French (fr-DJ)</option>
											<option value="lang_dm">Dominica &ndash; English (en-DM)</option>
											<option value="lang_do">Dominican Republic &ndash; Spanish (es-DO)</option>
											<option value="lang_ec">Ecuador &ndash; Spanish (es-EC)</option>
											<option value="lang_eg">Egypt &ndash; Arabic (ar-EG)</option>
											<option value="lang_eg">Egypt &ndash; English (en-EG)</option>
											<option value="lang_sp">El Salvador &ndash; Spanish (es-SP)</option>
											<option value="lang_ee">Estonia &ndash; Estonian (et-EE)</option>
											<option value="lang_et">Estonia &ndash; Russian (ru-ET)</option>
											<option value="lang_et">Ethiopia &ndash; Amharic (am-ET)</option>
											<option value="lang_fj">Fiji &ndash; English (en-FJ)</option>
											<option value="lang_fi">Finland &ndash; Swedish (sv-FI)</option>
											<option value="lang_ga">Gabon &ndash; French (fr-GA)</option>
											<option value="lang_gm">Gambia &ndash; English (en-GM)</option>
											<option value="lang_ge">Georgia &ndash; Kartuli (ka-GE)</option>
											<option value="lang_gh">Ghana &ndash; English (en-GH)</option>
											<option value="lang_gi">Gibraltar &ndash; English (en-GI)</option>
											<option value="lang_gl">Greenland &ndash; Danish (da-GL)</option>
											<option value="lang_gp">Guadeloupe &ndash; French (fr-GP)</option>
											<option value="lang_gt">Guatemala &ndash; Spanish (es-GT)</option>
											<option value="lang_gg">Guernsey &ndash; English (en-GG)</option>
											<option value="lang_gy">Guyana &ndash; English (en-GY)</option>
											<option value="lang_ht">Haiti &ndash; French (fr-HT)</option>
											<option value="lang_hn">Honduras &ndash; Spanish (es-HN)</option>
											<option value="lang_hk-hk">Hong Kong &ndash; Chinese (zh-HK-HK)</option>
											<option value="lang_hk">Hong Kong &ndash; English (en-HK)</option>
											<option value="lang_hu">Hungary &ndash; Hungarian (hu-HU)</option>
											<option value="lang_is">Iceland &ndash; Icelandic (is-IS)</option>
											<option value="lang_in">India &ndash; Hindi (hi-IN)</option>
											<option value="lang_in">India &ndash; Kannada (ka-IN)</option>
											<option value="lang_in">India &ndash; Malayalam (ml-IN)</option>
											<option value="lang_in">India &ndash; Marathi (mr-IN)</option>
											<option value="lang_in">India &ndash; Tamil (ta-IN)</option>
											<option value="lang_in">India &ndash; Telugu (te-IN)</option>
											<option value="lang_in">India &ndash; Bengali (be-IN)</option>
											<option value="lang_id">Indonesia &ndash; Javanese (jw-ID)</option>
											<option value="lang_iq">Iraq &ndash; Arabic (ar-IQ)</option>
											<option value="lang_ie">Ireland &ndash; Irish (ga-IE)</option>
											<option value="lang_im">Isle of Man &ndash; English (en-IM)</option>
											<option value="lang_jm">Jamaica &ndash; English (en-JM)</option>
											<option value="lang_cd">Jamhuri ya Kidemokrasia ya Kongo &ndash; Kiswahili (sw-CD)</option>
											<option value="lang_jp">Japan &ndash; Japanese (ja-JP)</option>
											<option value="lang_je">Jersey &ndash; English (en-JE)</option>
											<option value="lang_jo">Jordan &ndash; Arabic (ar-JO)</option>
											<option value="lang_jo">Jordan &ndash; English (en-JO)</option>
											<option value="lang_kz">Kazakhstan &ndash; Kazakh (kk-KZ)</option>
											<option value="lang_kz">Kazakhstan &ndash; Russian (ru-KZ)</option>
											<option value="lang_ke">Kenya &ndash; English (en-KE)</option>
											<option value="lang_ck">Kenya &ndash; Swahili (sw-CK)</option>
											<option value="lang_ki">Kiribati &ndash; English (en-KI)</option>
											<option value="lang_kr">Korea &ndash; Korean (ko-KR)</option>
											<option value="lang_kw">Kuwait &ndash; Arabic (ar-KW)</option>
											<option value="lang_kg">Kyrgyzstan &ndash; Kyrgyz (ky-KG)</option>
											<option value="lang_la">Laos &ndash; Lao (lo-LA)</option>
											<option value="lang_lv">Latvia &ndash; Latvian (lv-LV)</option>
											
											
											<option value="lang_lb">Lebanon &ndash; Arabic (ar-LB)</option>
											<option value="lang_ls">Lesotho &ndash; Sesotho (st-LS)</option>
											<option value="lang_ly">Libya &ndash; Arabic (ar-LY)</option>
											<option value="lang_li">Liechtenstein</option>
											<option value="lang_lu">Luxembourg</option>
											<option value="lang_mk">Macedonia &ndash; Macedonian (mk-MK)</option>
											<option value="lang_mg">Madagascar &ndash; Malagasy (mg-MG)</option>
											<option value="lang_mw">Malawi &ndash; Swahili (ny-MW)</option>
											<option value="lang_my">Malaysia &ndash; Malay (ms-MY)</option>
											<option value="lang_mv">Maldives &ndash; English (en-MV)</option>
											<option value="lang_ml">Mali &ndash; French (fr-ML)</option>
											<option value="lang_mt">Malta</option>
											
											<option value="lang_mu">Mauritius &ndash; English (en-MU)</option>
											<option value="lang_fm">Micronesia &ndash; English (en-FM)</option>
											<option value="lang_md">Moldova &ndash; Moldovan (mo-MD)</option>
											
											<option value="lang_mn">Mongolia &ndash; Mongolian (mn-MN)</option>
											<option value="lang_ms">Montserrat &ndash; English (en-MS)</option>
											<option value="lang_ma">Morocco &ndash; French (fr-MA)</option>
											<option value="lang_mz">Mozambique &ndash; Portuguese (pt-MZ)</option>
											<option value="lang_nr">Nauru &ndash; English (en-NR)</option>
											<option value="lang_np">Nepal &ndash; Hindi (ne-NP)</option>
											<option value="lang_nz">New Zealand &ndash; Maori (mi-NZ)</option>
											<option value="lang_ni">Nicaragua &ndash; Spanish (es-NI)</option>
											<option value="lang_ne">Niger &ndash; French (fr-NE)</option>
											<option value="lang_ng">Nigeria &ndash; English (en-NG)</option>
											<option value="lang_ng">Nigeria &ndash; Hausa (ha-NG)</option>
											<option value="lang_ng">Nigeria &ndash; Igbo (ig-NG)</option>
											
											<option value="lang_na">Namibia</option>
											<option value="lang_nu">Niue &ndash; English (en-NU)</option>
											<option value="lang_nf">Norfolk Island &ndash; English (en-NF)</option>
											<option value="lang_om">Oman</option>
											
											<option value="lang_bk">Pakistan &ndash; English (en-BK)</option>
											<option value="lang_ps">Palestine &ndash; Arabic (ar-PS)</option>
											<option value="lang_pa">Panama &ndash; Spanish (es-PA)</option>
											<option value="lang_py">Paraguay &ndash; Spanish (es-PY)</option>
											<option value="lang_pe">Peru &ndash; Spanish (es-PE)</option>
											<option value="lang_ph">Philippines &ndash; Tagalog (tl-PH)</option>
											<option value="lang_pn">Pitcairn Island &ndash; English (en-PN)</option>
											<option value="lang_pr">Puerto Rico</option>
											
											<option value="lang_qa">Qatar</option>
											
											<option value="lang_cd">Rep Dem du Congo &ndash; French (fr-CD)</option>
											<option value="lang_cg">Republic of the Congo &ndash; French (fr-CG)</option>
											<option value="lang_ro">Romania &ndash; Hungarian (hu-RO)</option>
											<option value="lang_rw">Rwanda &ndash; English (en-RW)</option>
											<option value="lang_sh">Saint Helena &ndash; English (en-SH)</option>
											<option value="lang_vc">Saint Vincent and the Grenadines &ndash; English (en-VC)</option>
											<option value="lang_sm">San Marino &ndash; Italian (it-SM)</option>
											<option value="lang_ws">Samoa &ndash; English (en-WS)</option>
											<option value="lang_st">Sao Tome and Principe &ndash; Portuguese (pt-ST)</option>
											<option value="lang_sa">Saudi Arabia &ndash; English (en-SA)</option>
											<option value="lang_sn">Senegal &ndash; French (fr-SN)</option>
											<option value="lang_sc">Seychelles &ndash; Seychellois Creole (cr-SC)</option>
											<option value="lang_sl">Sierra Leone &ndash; English (en-SL)</option>
											<option value="lang_cn-sg">Singapore </option>
											
											
											<option value="lang_sb">Solomon Islands &ndash; English (en-SB)</option>
											<option value="lang_so">Somalia &ndash; Somali (so-SO)</option>
											<option value="lang_za">South Africa &ndash; IsiXhosa (xh-ZA)</option>
											<option value="lang_za">South Africa &ndash; IsiZulu (zu-ZA)</option>
											<option value="lang_ct">Spain &ndash; Catalan (ca-CT)</option>
											<option value="lang_lk">Sri Lanka &ndash; English (en-LK)</option>
											
											<option value="lang_cn-tw">Taiwan</option>
											
											
											<option value="lang_tj">Tajikistan &ndash; Tajik (tg-TJ)</option>
											<option value="lang_tz">Tanzania &ndash; Swahili (sw-TZ)</option>
											<option value="lang_tl">Timor-Leste &ndash; Portuguese (pt-TL)</option>
											<option value="lang_tg">Togo</option>
											<option value="lang_tk">Tokelau &ndash; English (en-TK)</option>
											<option value="lang_to">Tonga &ndash; English (en-TO)</option>
											<option value="lang_tt">Trinidad and Tobago (en-TT)</option>
											<option value="lang_tn">Tunisia</option>
											
											<option value="lang_tm">Turkmenistan &ndash; Turkmen (tk-TM)</option>
											<option value="lang_ug">Uganda &ndash; English (en-UG)</option>
											<option value="lang_ua">Ukraine</option>
											
											<option value="lang_ae">United Arab Emirates &ndash; English (en-AE)</option>
											<option value="lang_uy">Uruguay &ndash; Spanish (es-UY)</option>
											<option value="lang_uz">Uzbekistan &ndash; Uzbek (uz-UZ)</option>
											<option value="lang_vu">Vanuatu &ndash; English (en-VU)</option>
											<option value="lang_ve">Venezuela &ndash; Spanish (es-VE)</option>
											
											<option value="lang_vn">Vietnam</option>
											
											<option value="lang_vi">Virgin Islands &ndash; English (en-VI)</option>
											<option value="lang_zm">Zambia &ndash; English (en-ZM)</option>
											<option value="lang_zw">Zimbabwe &ndash; English (en-ZW)</option>
											</select><br><br>
	<span style="color:red;">This field is required only for keyword position</span><br>										<span style="font-weight:bold; font-size:large; ">Nation : </span> <select  id="locale" name="locale">
											<option value="en-us">United States &ndash; English (en-US)</option>
											<option value="en-uk">United Kingdom &ndash; English (en-UK)</option>
											<option value="en-au">Australia &ndash; English (en-AU)</option>
											<option value="de-de">Germany &ndash; German (de-DE)</option>
											<option value="nl-nl">Netherlands &ndash; Dutch (nl-NL)</option>
											<option value="th-th">Thailand &ndash; Thai (th-TH)</option>
											<option value="en-ca">Canada &ndash; English (en-CA)</option>
											<option value="tr-tr">Turkey &ndash; Turkish (tr-TR)</option>
											<option value="sv-se">Sweden &ndash; Swedish (sv-SE)</option>
											<option value="da-dk">Denmark &ndash; Danish (da-DK)</option>
											<option value="en-in">India &ndash; English (en-IN)</option>
											<option value="en-ie">Ireland &ndash; English (en-IE)</option>
											<option value="en-za">South Africa &ndash; English (en-ZA)</option>
											<option value="es-es">Spain &ndash; Spanish (es-ES)</option>
											<option value="ro-ro">Romania &ndash; Romanian (ro-RO)</option>
											<option value="en-sg">Singapore &ndash; English (en-SG)</option>
											<option value="id-id">Indonesia &ndash; Indonesian (id-ID)</option>
											<option value="pt-br">Brazil &ndash; Portuguese (pt-BR)</option>
											<option value="it-it">Italy &ndash; Italian (it-IT)</option>
											<option value="fr-ca">Canada &ndash; French (fr-CA)</option>
											<option value="fr-fr">France &ndash; French (fr-FR)</option>
											<option value="es-mx">Mexico &ndash; Spanish (es-MX)</option>
											<option value="fi-fl">Finland &ndash; Finnish (fi-FL)</option>
											<option value="pl-pl">Poland &ndash; Polish (pl-PL)</option>
											<option value="no-no">Norway &ndash; Norwegian (no-NO)</option>
											<option value="el-gr">Greece &ndash; Greek (el-GR)</option>
											<option value="en-nz">New Zealand &ndash; English (en-NZ)</option>
											<option value="en-ph">Philippines &ndash; English (en-PH)</option>
											<option value="de-ch">Switzerland &ndash; German (de-CH)</option>
											<option value="es-ar">Argentina &ndash; Spanish (es-AR)</option>
											<option value="ru-ru">Russia &ndash; Russian (ru-RU)</option>
											<option value="ar-ae">United Arab Emirates &ndash; Arabic (ar-AE)</option>
											<option value="he-il">Israel &ndash; Hebrew (he-IL)</option>
											<option value="en-my">Malaysia &ndash; English (en-MY)</option>
											<option value="es-cl">Chile &ndash; Spanish (es-CL)</option>
											<option value="sk-sk">Slovakia &ndash; Slovak (sk-SK)</option>
											<option value="de-at">Austria &ndash; German (de-AT)</option>
											<option value="sl-si">Slovenia &ndash; Slovenian (sl-SI)</option>
											<option value="en-th">Thailand &ndash; English (en-TH)</option>
											<option value="en-id">Indonesia &ndash; English (en-ID)</option>
											<option value="zh-cn-hk">China &ndash; Chinese (Simplified) (zh-CN-HK)</option>
											<option value="en-ch">Switzerland &ndash; English (en-CH)</option>
											<option value="ar-il">Israel &ndash; Arabic (ar-IL)</option>
											<option value="pt-pt">Portugal &ndash; Portuguese (pt-PT)</option>
											<option value="es-us">United States &ndash; Spanish (es-US)</option>
											<option value="hr-hr">Croatia &ndash; Croatian (hr-HR)</option>
											<option value="en-il">Israel &ndash; English (en-IL)</option>
											<option value="af-za">South Africa &ndash; Afrikaans (af-ZA)</option>
											<option value="en-be">Belgium &ndash; English (en-BE)</option>
											<option value="ar-sa">Saudi Arabia &ndash; Arabic (ar-SA)</option>
											<option value="de-ro">Romania &ndash; German (de-RO)</option>
											<option value="fr-ch">Switzerland &ndash; French (fr-CH)</option>
											<option value="en-vn">Vietnam &ndash; English (en-VN)</option>
											<option value="lt-lt">Lithuania &ndash; Lithuanian (lt-LT)</option>
											<option value="sr-rs">Serbia &ndash; Serbian (sr-RS)</option>
											<option value="ps-af">Afghanistan &ndash; Persian (ps-AF)</option>
											<option value="fr-dz">Algeria &ndash; French (fr-DZ)</option>
											<option value="en-as">American Samoa &ndash; English (en-AS)</option>
											<option value="ca-ad">Andorra &ndash; Catalan (ca-AD)</option>
											<option value="pt-ao">Angola &ndash; Portuguese (pt-AO)</option>
											<option value="en-ai">Anguilla &ndash; English (en-AI)</option>
											<option value="en-ag">Antigua and Barbuda &ndash; English (en-AG)</option>
											<option value="hy-am">Armenia &ndash; Armenian (hy-AM)</option>
											<option value="az-az">Azerbaijan &ndash; Azerbaijani (az-AZ)</option>
											<option value="en-bs">Bahamas &ndash; English (en-BS)</option>
											<option value="ar-bh">Bahrain &ndash; Arabic (ar-BH)</option>
											<option value="en-bh">Bahrain &ndash; English (en-BH)</option>
											<option value="bn-bd">Bangladesh &ndash; Bengali (bn-BD)</option>
											<option value="be-by">Belarus &ndash; Belarusian (be-BY)</option>
											<option value="nl-be">Belgium &ndash; Dutch (nl-BE)</option>
											<option value="fr-be">Belgium &ndash; French (fr-BE)</option>
											<option value="de-be">Belgium &ndash; German (de-BE)</option>
											<option value="en-bz">Belize &ndash; English (en-BZ)</option>
											<option value="fr-bj">Benin &ndash; French (fr-BJ)</option>
											<option value="es-bo">Bolivia &ndash; Spanish (es-BO)</option>
											<option value="bs-ba">Bosnia and Herzegovina &ndash; Bosnian (bs-BA)</option>
											<option value="tn-bw">Botswana &ndash; Tswana (tn-BW)</option>
											<option value="en-vg">British Virgin Islands &ndash; English (en-VG)</option>
											<option value="ms-bn">Brunei &ndash; Malay (ms-BN)</option>
											<option value="bg-bg">Bulgaria &ndash; Bulgarian (bg-BG)</option>
											<option value="fr-bf">Burkina Faso &ndash; French (fr-BF)</option>
											<option value="fr-bi">Burundi &ndash; French (fr-BI)</option>
											<option value="km-kh">Cambodia &ndash; Khmer (km-KH)</option>
											<option value="fr-cm">Cameroon &ndash; French (fr-CM)</option>
											<option value="pt-cv">Cape Verde &ndash; Portuguese (pt-CV)</option>
											<option value="fr-cf">Central African Republic &ndash; French (fr-CF)</option>
											<option value="fr-td">Chad &ndash; French (fr-TD)</option>
											<option value="en-cc">Cocos Islands &ndash; English (en-CC)</option>
											<option value="es-co">Colombia &ndash; Spanish (es-CO)</option>
											<option value="en-ck">Cook Islands &ndash; English (en-CK)</option>
											<option value="es-cr">Costa Rica &ndash; Spanish (es-CR)</option>
											<option value="fr-ci">C&#244;te d\'Ivoire &ndash; French (fr-CI)</option>
											<option value="es-cu">Cuba &ndash; Spanish (es-CU)</option>
											<option value="cs-cz">Czech Republic &ndash; Czech (cs-CZ)</option>
											<option value="fr-dj">Djibouti &ndash; French (fr-DJ)</option>
											<option value="en-dm">Dominica &ndash; English (en-DM)</option>
											<option value="es-do">Dominican Republic &ndash; Spanish (es-DO)</option>
											<option value="es-ec">Ecuador &ndash; Spanish (es-EC)</option>
											<option value="ar-eg">Egypt &ndash; Arabic (ar-EG)</option>
											<option value="en-eg">Egypt &ndash; English (en-EG)</option>
											<option value="es-sp">El Salvador &ndash; Spanish (es-SP)</option>
											<option value="et-ee">Estonia &ndash; Estonian (et-EE)</option>
											<option value="ru-et">Estonia &ndash; Russian (ru-ET)</option>
											<option value="am-et">Ethiopia &ndash; Amharic (am-ET)</option>
											<option value="en-fj">Fiji &ndash; English (en-FJ)</option>
											<option value="sv-fi">Finland &ndash; Swedish (sv-FI)</option>
											<option value="fr-ga">Gabon &ndash; French (fr-GA)</option>
											<option value="en-gm">Gambia &ndash; English (en-GM)</option>
											<option value="ka-ge">Georgia &ndash; Kartuli (ka-GE)</option>
											<option value="en-gh">Ghana &ndash; English (en-GH)</option>
											<option value="en-gi">Gibraltar &ndash; English (en-GI)</option>
											<option value="da-gl">Greenland &ndash; Danish (da-GL)</option>
											<option value="fr-gp">Guadeloupe &ndash; French (fr-GP)</option>
											<option value="es-gt">Guatemala &ndash; Spanish (es-GT)</option>
											<option value="en-gg">Guernsey &ndash; English (en-GG)</option>
											<option value="en-gy">Guyana &ndash; English (en-GY)</option>
											<option value="fr-ht">Haiti &ndash; French (fr-HT)</option>
											<option value="es-hn">Honduras &ndash; Spanish (es-HN)</option>
											<option value="zh-hk-hk">Hong Kong &ndash; Chinese (zh-HK-HK)</option>
											<option value="en-hk">Hong Kong &ndash; English (en-HK)</option>
											<option value="hu-hu">Hungary &ndash; Hungarian (hu-HU)</option>
											<option value="is-is">Iceland &ndash; Icelandic (is-IS)</option>
											<option value="hi-in">India &ndash; Hindi (hi-IN)</option>
											<option value="ka-in">India &ndash; Kannada (ka-IN)</option>
											<option value="ml-in">India &ndash; Malayalam (ml-IN)</option>
											<option value="mr-in">India &ndash; Marathi (mr-IN)</option>
											<option value="ta-in">India &ndash; Tamil (ta-IN)</option>
											<option value="te-in">India &ndash; Telugu (te-IN)</option>
											<option value="be-in">India &ndash; Bengali (be-IN)</option>
											<option value="jw-id">Indonesia &ndash; Javanese (jw-ID)</option>
											<option value="ar-iq">Iraq &ndash; Arabic (ar-IQ)</option>
											<option value="ga-ie">Ireland &ndash; Irish (ga-IE)</option>
											<option value="en-im">Isle of Man &ndash; English (en-IM)</option>
											<option value="en-jm">Jamaica &ndash; English (en-JM)</option>
											<option value="sw-cd">Jamhuri ya Kidemokrasia ya Kongo &ndash; Kiswahili (sw-CD)</option>
											<option value="ja-jp">Japan &ndash; Japanese (ja-JP)</option>
											<option value="en-je">Jersey &ndash; English (en-JE)</option>
											<option value="ar-jo">Jordan &ndash; Arabic (ar-JO)</option>
											<option value="en-jo">Jordan &ndash; English (en-JO)</option>
											<option value="kk-kz">Kazakhstan &ndash; Kazakh (kk-KZ)</option>
											<option value="ru-kz">Kazakhstan &ndash; Russian (ru-KZ)</option>
											<option value="en-ke">Kenya &ndash; English (en-KE)</option>
											<option value="sw-ck">Kenya &ndash; Swahili (sw-CK)</option>
											<option value="en-ki">Kiribati &ndash; English (en-KI)</option>
											<option value="ko-kr">Korea &ndash; Korean (ko-KR)</option>
											<option value="ar-kw">Kuwait &ndash; Arabic (ar-KW)</option>
											<option value="ky-kg">Kyrgyzstan &ndash; Kyrgyz (ky-KG)</option>
											<option value="lo-la">Laos &ndash; Lao (lo-LA)</option>
											<option value="lv-lv">Latvia &ndash; Latvian (lv-LV)</option>
											<option value="lt-lv">Latvia &ndash; Lithuanian (lt-LV)</option>
											<option value="ru-lv">Latvia &ndash; Russian (ru-LV)</option>
											<option value="ar-lb">Lebanon &ndash; Arabic (ar-LB)</option>
											<option value="en-lb">Lebanon &ndash; English (en-LB)</option>
											<option value="fr-lb">Lebanon &ndash; French (fr-LB)</option>
											<option value="st-ls">Lesotho &ndash; Sesotho (st-LS)</option>
											<option value="ar-ly">Libya &ndash; Arabic (ar-LY)</option>
											<option value="de-li">Liechtenstein &ndash; German (de-LI)</option>
											<option value="de-lu">Luxembourg &ndash; German (de-LU)</option>
											<option value="mk-mk">Macedonia &ndash; Macedonian (mk-MK)</option>
											<option value="mg-mg">Madagascar &ndash; Malagasy (mg-MG)</option>
											<option value="ny-mw">Malawi &ndash; Swahili (ny-MW)</option>
											<option value="ms-my">Malaysia &ndash; Malay (ms-MY)</option>
											<option value="en-mv">Maldives &ndash; English (en-MV)</option>
											<option value="fr-ml">Mali &ndash; French (fr-ML)</option>
											<option value="en-mt">Malta &ndash; English (en-MT)</option>
											<option value="mt-mt">Malta &ndash; Maltese (mt-MT)</option>
											<option value="en-mu">Mauritius &ndash; English (en-MU)</option>
											<option value="en-fm">Micronesia &ndash; English (en-FM)</option>
											<option value="mo-md">Moldova &ndash; Moldovan (mo-MD)</option>
											<option value="ru-md">Moldova &ndash; Russian (ru-MD)</option>
											<option value="mn-mn">Mongolia &ndash; Mongolian (mn-MN)</option>
											<option value="en-ms">Montserrat &ndash; English (en-MS)</option>
											<option value="fr-ma">Morocco &ndash; French (fr-MA)</option>
											<option value="pt-mz">Mozambique &ndash; Portuguese (pt-MZ)</option>
											<option value="en-nr">Nauru &ndash; English (en-NR)</option>
											<option value="ne-np">Nepal &ndash; Hindi (ne-NP)</option>
											<option value="mi-nz">New Zealand &ndash; Maori (mi-NZ)</option>
											<option value="es-ni">Nicaragua &ndash; Spanish (es-NI)</option>
											<option value="fr-ne">Niger &ndash; French (fr-NE)</option>
											<option value="en-ng">Nigeria &ndash; English (en-NG)</option>
											<option value="ha-ng">Nigeria &ndash; Hausa (ha-NG)</option>
											<option value="ig-ng">Nigeria &ndash; Igbo (ig-NG)</option>
											<option value="yo-ng">Nigeria &ndash; Yoruba (yo-NG)</option>
											<option value="en-na">Namibia &ndash; English (en-NA)</option>
											<option value="en-nu">Niue &ndash; English (en-NU)</option>
											<option value="en-nf">Norfolk Island &ndash; English (en-NF)</option>
											<option value="ar-om">Oman &ndash; Arabic (ar-OM)</option>
											<option value="en-om">Oman &ndash; English (en-OM)</option>
											<option value="en-bk">Pakistan &ndash; English (en-BK)</option>
											<option value="ar-ps">Palestine &ndash; Arabic (ar-PS)</option>
											<option value="es-pa">Panama &ndash; Spanish (es-PA)</option>
											<option value="es-py">Paraguay &ndash; Spanish (es-PY)</option>
											<option value="es-pe">Peru &ndash; Spanish (es-PE)</option>
											<option value="tl-ph">Philippines &ndash; Tagalog (tl-PH)</option>
											<option value="en-pn">Pitcairn Island &ndash; English (en-PN)</option>
											<option value="en-pr">Puerto Rico &ndash; English (en-PR)</option>
											<option value="es-pr">Puerto Rico &ndash; Spanish (es-PR)</option>
											<option value="ar-qa">Qatar &ndash; Arabic (ar-QA)</option>
											<option value="en-qa">Qatar &ndash; English (en-QA)</option>
											<option value="fr-cd">Rep Dem du Congo &ndash; French (fr-CD)</option>
											<option value="fr-cg">Republic of the Congo &ndash; French (fr-CG)</option>
											<option value="hu-ro">Romania &ndash; Hungarian (hu-RO)</option>
											<option value="en-rw">Rwanda &ndash; English (en-RW)</option>
											<option value="en-sh">Saint Helena &ndash; English (en-SH)</option>
											<option value="en-vc">Saint Vincent and the Grenadines &ndash; English (en-VC)</option>
											<option value="it-sm">San Marino &ndash; Italian (it-SM)</option>
											<option value="en-ws">Samoa &ndash; English (en-WS)</option>
											<option value="pt-st">Sao Tome and Principe &ndash; Portuguese (pt-ST)</option>
											<option value="en-sa">Saudi Arabia &ndash; English (en-SA)</option>
											<option value="fr-sn">Senegal &ndash; French (fr-SN)</option>
											<option value="cr-sc">Seychelles &ndash; Seychellois Creole (cr-SC)</option>
											<option value="en-sl">Sierra Leone &ndash; English (en-SL)</option>
											<option value="zh-cn-sg">Singapore &ndash; Chinese (zh-CN-SG)</option>
											<option value="ms-sg">Singapore &ndash; Malay (ms-SG)</option>
											<option value="ta-sg">Singapore &ndash; Tamil (ta-SG)</option>
											<option value="en-sb">Solomon Islands &ndash; English (en-SB)</option>
											<option value="so-so">Somalia &ndash; Somali (so-SO)</option>
											<option value="xh-za">South Africa &ndash; IsiXhosa (xh-ZA)</option>
											<option value="zu-za">South Africa &ndash; IsiZulu (zu-ZA)</option>
											<option value="ca-ct">Spain &ndash; Catalan (ca-CT)</option>
											<option value="en-lk">Sri Lanka &ndash; English (en-LK)</option>
											<option value="nl-ch">Switzerland &ndash; Dutch (nl-CH)</option>
											<option value="it-ch">Switzerland &ndash; Italian (it-CH)</option>
											<option value="rm-ch">Switzerland &ndash; Rumantsch (rm-CH)</option>
											<option value="zh-cn-tw">Taiwan &ndash; Chinese (zh-CN-TW)</option>
											<option value="zh-tw-tw">Taiwan &ndash; Chinese Traditional Han (zh-TW-TW)</option>
											<option value="en-tw">Taiwan &ndash; English (en-TW)</option>
											<option value="tg-tj">Tajikistan &ndash; Tajik (tg-TJ)</option>
											<option value="sw-tz">Tanzania &ndash; Swahili (sw-TZ)</option>
											<option value="pt-tl">Timor-Leste &ndash; Portuguese (pt-TL)</option>
											<option value="fr-tg">Togo &ndash; French (fr-TG)</option>
											<option value="en-tk">Tokelau &ndash; English (en-TK)</option>
											<option value="en-to">Tonga &ndash; English (en-TO)</option>
											<option value="en-tt">Trinidad and Tobago (en-TT)</option>
											<option value="ar-tn">Tunisia &ndash; Arabic (ar-TN)</option>
											<option value="fr-tn">Tunisia &ndash; French (fr-TN)</option>
											<option value="tk-tm">Turkmenistan &ndash; Turkmen (tk-TM)</option>
											<option value="en-ug">Uganda &ndash; English (en-UG)</option>
											<option value="en-ua">Ukraine &ndash; English (en-UA)</option>
											<option value="ru-ua">Ukraine &ndash; Russian (ru-UA)</option>
											<option value="uk-ua">Ukraine &ndash; Ukrainian (uk-UA)</option>
											<option value="en-ae">United Arab Emirates &ndash; English (en-AE)</option>
											<option value="es-uy">Uruguay &ndash; Spanish (es-UY)</option>
											<option value="uz-uz">Uzbekistan &ndash; Uzbek (uz-UZ)</option>
											<option value="en-vu">Vanuatu &ndash; English (en-VU)</option>
											<option value="es-ve">Venezuela &ndash; Spanish (es-VE)</option>
											<option value="zh-cn-vn">Vietnam &ndash; Chinese (zh-CN-VN)</option>
											<option value="fr-vn">Vietnam &ndash; French (fr-VN)</option>
											<option value="vi-vn">Vietnam &ndash; Vietnamese (vi-VN)</option>
											<option value="en-vi">Virgin Islands &ndash; English (en-VI)</option>
											<option value="en-zm">Zambia &ndash; English (en-ZM)</option>
											<option value="en-zw">Zimbabwe &ndash; English (en-ZW)</option>
											</select>
